### ISSUE TITLE
module qcode-terminal

### ISSUE THREAD

**Issue by aqiyzx** [mrfzvx12/termux-whatsapp-bot#10]
internal/modules/cjs/loader.js:883
error err;
^

Error: Cannot find module 'qcode-terminal'
quir stack:
- /data/data/com.termux/files/home/termux-whatsapp-bot/index.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
  at Function.Module._load (internal/modules/cjs/loader.js:725:27)
  at Module.require (internal/modules/cjs/loader.js:952:19)

  at Object.<anonymous> (/data/data/com.termux/files/home/termux-whatsapp-bot/index.js:1:16)
  at Module._compile (internal/modules/cjs/loaders.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (internal/modules/cjs/loader.js:928:32)
  at Function.excecuteUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)

**Comment by mrfzvx12** [comment]
Qr nggk keluar?

Pada tanggal Sab, 30 Jan 2021 16.52, aqiyzx <notifications@github.com>
menulis:

**Comment by aqiyzx** [comment]
iya engga keluar
